#%RAML 1.0 NamedExample
account-example:
  billingCity: San Francisco
  billingCountry: United States
  billingCountryCode: USA
  billingPostalCode: 94105
  billingState: California
  billingStateCode: CA
  billingStreet: 415 Mission St