#%RAML 1.0 DataType
displayName: Account
type: object
properties:
  billingCity?:
    type: string
  billingCountry?:
    type: string
  billingCountryCode?:
    type: string
  billingPostalCode?:
    type: string
  billingState?:
    type: string
  billingStateCode?:
    type: string
  billingStreet?:
    type: string 